WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 750

WIDTH_UNIT = round(WINDOW_WIDTH / 100)
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

SCREEN_HEIGHT = round(WINDOW_HEIGHT * 0.7)

NUM_QUBITS=3

LEFT_EDGE = WIDTH_UNIT
RIGHT_EDGE = WINDOW_WIDTH - LEFT_EDGE

MEASUREMENT_COOLDOWN_TIME = 4000

WIN_SCORE = 1